pacman::p_load(pacman, dplyr, GGally, ggplot2, ggthemes, ggvis, httr, plotly, rio, rmarkdown, shiny, stringr, tidyr)
csv <- import(".../consulta_cand_2020_SC.csv")
View(csv)
head(csv)
describe(csv$NR_IDADE_DATA_POSSE)
hist(csv$NR_IDADE_DATA_POSSE, freq = FALSE, main = "NR IDADE DATA POSSE", xlab = "Idade")
curve(dnorm(x, mean = mean(csv$NR_IDADE_DATA_POSSE), sd = sd(csv$NR_IDADE_DATA_POSSE)), add = TRUE)
abline(v = mean(csv$NR_IDADE_DATA_POSSE), col = "red", lwd = 2.5)
rm(list = ls())
